function [data, auxData, metaData, txtData, weights] = mydata_Galaxias_occidentalis
% file generated by prt_mydata

%% set metaData
metaData.phylum     = 'Chordata';
metaData.class      = 'Actinopterygii';
metaData.order      = 'Osmeriformes';
metaData.family     = 'Galaxiidae';
metaData.species    = 'Galaxias_occidentalis';
metaData.species_en = 'Western galaxias';

metaData.ecoCode.climate = {'Csa','Csb'};
metaData.ecoCode.ecozone = {'TA','TO'};
metaData.ecoCode.habitat = {'0bFc','jpFr','jpFl','0bFp','0bFpe'};
metaData.ecoCode.embryo  = {'Fh'};
metaData.ecoCode.migrate = {'Mp'};
metaData.ecoCode.food    = {'biCi','biCik','biCvf'};
metaData.ecoCode.gender  = {'Dg'};
metaData.ecoCode.reprod  = {'O'};

metaData.T_typical  = C2K(16.5); % K, body temp

metaData.data_0     = {'tp','tpm','am','tp','tpm','tR','am','Lh','Lp','Lpm','Li','Lim','Ri','GSI','GSI','Wwh','Wwp','Wwpm','Wwi','Wwim'};
metaData.data_1     = {'tL_f','tL_f','tL_m','LN','WwN','LWw_f','LWd_m','LWw_m'};

metaData.COMPLETE   = 2.5; % using criteria of LikaKear2011

metaData.author     = {'Callum Donohue'};
metaData.date_subm  = [2023 5 31];
metaData.email      = {'callum.donohue@murdoch.edu.au'};
metaData.address    = {'Harry Butler Institute, Murdoch University'};

metaData.curator    = {'Starrlight Augustine'};
metaData.email_cur  = {'starrlight@tecnico.ulisboa.pt'};
metaData.date_acc   = [2023 6 1];

%% set zero-variate data
data.tp = 365; units.tp = 'd'; label.tp = 'time since birth at puberty'; bibkey.tp = {'pen1991biology1','morgan1998distribution'};
  temp.tp = C2K(17.5); units.temp.tp = 'K'; label.temp.tp = 'temperature';
  comment.tp = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. ';
data.tpm = 365; units.tpm = 'd'; label.tpm = 'time since birth at puberty for males'; bibkey.tpm = {'pen1991biology1','morgan1998distribution'};
  temp.tpm = C2K(17.5); units.temp.tpm = 'K'; label.temp.tpm = 'temperature';
  comment.tpm = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. ';
data.am = 1825; units.am = 'd'; label.am = 'life span'; bibkey.am = {'pen1991biology2'};
  temp.am = C2K(17.5); units.temp.am = 'K'; label.temp.am = 'temperature';
  comment.am = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. ';

data.Lh = 0.61; units.Lh = 'cm'; label.Lh = 'length at hatch'; bibkey.Lh = {'gill1994larval'};
  comment.Lh = 'Smallest larval stage recorded. Immediately after hatch may be smaller. ';
data.Lp = 7.5; units.Lp = 'cm'; label.Lp = 'length at puberty'; bibkey.Lp = {'pen1991biology2','morgan1998distribution'};
data.Lpm = 7; units.Lpm = 'cm'; label.Lpm = 'length at puberty for males'; bibkey.Lpm = {'pen1991biology2','morgan1998distribution'};
data.Li = 16.3; units.Li = 'cm'; label.Li = 'ultimate length'; bibkey.Li = {'pen1991biology2'};
  comment.Li = 'Apparently larger individuals have been found. Personal communications has suggested that a female of 19 cm has been seen. However, 16.3 cm is published alongside an ultimate weight. The weight of larger individuals is unknown. ';
data.Lim = 12.6; units.Lim = 'cm'; label.Lim = 'ultimate length for males'; bibkey.Lim = {'pen1991biology2'};

data.Ri = 4.21; units.Ri = '#/d'; label.Ri = 'ultimate reproduction rate'; bibkey.Ri = {'pen1991biology1'};
  temp.Ri = C2K(17.5); units.temp.Ri = 'K'; label.temp.Ri = 'temperature';
  comment.Ri = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. Rate = 1538 (annual fecunditiy at age 3) / 365 (e.g., ultimate fecundity; can also do mean fecudity over life = 905/365)';

data.Wwp = 2.8; units.Wwp = 'g'; label.Wwp = 'wet weight at puberty'; bibkey.Wwp = {'pen1991biology1'};
data.Wwi = 32; units.Wwi = 'g'; label.Wwi = 'ultimate wet weight'; bibkey.Wwi = {'pen1991biology2'};
data.Wwim = 12.1; units.Wwim = 'g'; label.Wwim = 'ultimate wet weight for males'; bibkey.Wwim = {'pen1991biology2'};

%% set uni-variate data
% time - length
data.tL_f = [ ... 
  0.106 28.92
  0.183 35.043
  0.281 42.085
  0.38 48.821
  0.511 56.168
  0.686 63.21
  0.872 70.558
  1.058 76.681
  1.222 81.886
  1.397 87.091
  1.583 91.989
  1.791 96.275
  1.977 100.255
  2.24 104.236
  2.579 108.828
  2.875 111.889
  3.236 114.645
  3.542 116.482
  3.859 117.707
  4.133 119.237
  4.374 120.156
  4.614 121.074
  4.877 121.993
  5.008 122.605];
units.tL_f = {'d', 'cm'}; label.tL_f = {'time', 'length'};
temp.tL_f = C2K(17.5); units.temp.tL_f = 'K'; label.temp.tL_f = 'temperature';
bibkey.tL_f = {'pen1991biology2'};
comment.tL_f = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. ';

% time - length
data.tL_m = [ ... 
  0.06 30.084
  0.126 33.758
  0.264 40.922
  0.415 47.351
  0.546 53.413
  0.684 58.924
  0.822 63.884
  0.986 69.027
  1.186 74.538
  1.405 79.568
  1.632 84.16
  1.89 88.534
  2.187 92.689
  2.437 95.751
  2.703 97.719
  2.953 99.687
  3.211 101.436
  3.461 102.53
  3.742 103.842
  4.008 104.717];
units.tL_m = {'d', 'cm'}; label.tL_m = {'time', 'length'};
temp.tL_m = C2K(17.5); units.temp.tL_m = 'K'; label.temp.tL_m = 'temperature';
bibkey.tL_m = {'pen1991biology2'};
comment.tL_m = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. ';

% length - yearly fecundity
data.LN = [ ... 
  50.84 130.942
  52.652 165.406
  54.677 195.949
  56.808 226.469
  57.771 288.236
  58.354 262.928
  59.154 289.868
  59.268 380.876
  60.484 285.701
  61.98 349.288
  62.084 324.086
  63.002 486.58
  63.041 312.253
  63.259 379.995
  63.842 348.877
  64.17 455.333
  64.698 406.794
  65.01 315.693
  65.074 451.259
  65.172 346.647
  66.201 569.16
  66.303 511.032
  66.37 681.462
  66.609 350.203
  66.972 224.227
  67.007 656.142
  67.215 605.737
  67.251 390.736
  67.418 485.606
  67.99 309.225
  68.063 557.128
  68.1 359.559
  68.266 440.871
  68.323 479.596
  68.331 586.122
  68.44 619.025
  69.333 467.752
  69.353 711.794
  69.392 537.466
  70.128 424.965
  70.178 395.901
  70.618 564.312
  71.143 475.1
  71.207 616.478
  71.213 682.33
  71.221 783.046
  71.411 498.283
  72.004 600.807
  72.291 195.937
  72.368 486.451
  72.805 637.431
  73.384 557.891
  73.464 887.142
  73.486 497.826
  73.654 602.38
  73.842 956.786
  74.174 455.063
  74.23 1148.45
  74.301 704.891
  74.441 1125.16
  74.724 667.998
  75.194 563.303
  75.738 708.448
  76.149 524.355
  76.373 657.95
  76.546 832.23
  76.554 931.008
  76.965 744.978
  77.069 719.776
  77.167 609.352
  77.2 1016.09
  77.281 1368.58
  77.385 1339.51
  77.564 915.291
  78.299 787.295
  78.345 698.189
  78.383 514.177
  79.685 825.727
  80.044 647.455
  80.123 967.022
  80.159 755.895
  81.064 769.253
  81.176 829.272
  82.233 743.816
  82.436 1282.22
  83.293 1345.95
  83.348 704.833
  83.549 1658.63
  83.998 855.765
  84.028 561.354
  84.086 1283.8
  86.521 1118.62
  86.888 1050.75
  86.912 694.362
  86.993 382.508
  87.016 661.412
  87.048 1064.28
  87.075 1397.41
  87.135 820.209
  87.27 1168.82
  88.019 564.347
  88.203 860.648
  88.211 963.301
  89.26 769.382
  90.578 618.015
  91.182 1614.6
  91.194 997.506
  91.216 1266.73
  92.544 1243.19
  92.591 1953.11
  92.651 1802.21
  93.558 1279.77
  94.062 932.957
  94.209 1426.83
  95.483 1391.68
  96.474 1143.54
  97.19 783.128
  97.739 1764.03
  98.14 686.075
  98.457 2542.11
  99.267 802.039
  99.463 1255.22
  100.323 703.025
  100.496 1681.37
  100.593 1983.11
  102.059 1217.79
  102.44 1440.06
  103.446 1291.6
  104.607 2151.64
  104.615 1352.22
  104.75 1227.78
  105.315 1018.54
  105.365 2537.94
  106.479 1923.58
  106.505 1346.51
  107.435 1155.72
  107.646 1957.73
  107.751 1465.35
  108.246 1290.54
  108.341 1557.87
  110.278 2129.21
  112.174 2197.61
  113.522 1781.73];
units.LN = {'cm', '#'}; label.LN = {'length', 'yearly fecundity'};
temp.LN = C2K(17.5); units.temp.LN = 'K'; label.temp.LN = 'temperature';
bibkey.LN = {'pen1991biology1'};
comment.LN = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. ';

% wet weight - yearly fecundity
data.WwN = [ ... 
  1.04 234.974
  1.15 383.129
  1.213 290.437
  1.398 566.259
  1.423 319.403
  1.444 369.682
  1.525 357.711
  1.566 317.976
  1.636 500.572
  1.656 466.808
  1.682 353.627
  1.695 228.545
  1.724 395.288
  1.773 514.371
  1.812 371.401
  1.813 428.974
  1.884 677.085
  1.91 561.919
  1.937 611.531
  1.963 466.586
  1.982 305.764
  2.053 579.683
  2.066 468.497
  2.067 631.29
  2.075 670.991
  2.092 395.022
  2.117 192.504
  2.148 484.321
  2.163 692.765
  2.176 565.697
  2.23 504.114
  2.231 611.319
  2.321 791.916
  2.341 720.431
  2.408 563.545
  2.411 895.086
  2.484 656.798
  2.51 545.603
  2.587 714.298
  2.599 567.377
  2.637 928.673
  2.646 527.637
  2.741 458.083
  2.763 606.964
  2.792 803.487
  2.868 843.139
  2.876 934.457
  2.908 785.536
  2.926 505.597
  2.928 725.963
  2.987 1142.83
  3.057 658.37
  3.059 866.824
  3.207 1297.53
  3.223 846.853
  3.228 733.687
  3.255 1347.12
  3.282 662.178
  3.306 1029.44
  3.351 757.422
  3.385 1392.69
  3.399 703.785
  3.49 963.793
  3.535 701.701
  3.55 832.72
  3.57 743.368
  3.593 1062.98
  3.62 967.67
  3.671 1289.25
  3.753 1370.59
  3.803 878.199
  3.843 1424.13
  3.887 393.727
  3.898 840.41
  4.018 1640
  4.121 582.161
  4.177 715.135
  4.183 679.395
  4.29 1141.89
  4.306 639.601
  4.366 1199.41
  4.488 1687.31
  4.491 784.393
  4.495 1179.46
  4.589 1018.59
  4.892 635.207
  4.964 1261.32
  4.99 795.945
  5.053 958.694
  5.165 577.437
  5.366 1086.32
  5.534 1445.14
  5.651 1171.88
  5.843 1829.27
  5.892 1282.88
  5.92 717.451
  5.938 1422.61
  5.973 1708.47
  6.255 1463.68
  6.379 828.295
  6.406 1285.69
  6.531 1787.48
  6.536 1247.48
  6.555 2003.46
  6.62 1965.3
  6.902 707.212
  6.908 1317.09
  7.104 1256.6
  7.314 2571.5
  7.324 1367.61
  7.675 1592.89
  7.69 1980.41
  7.816 2555.26
  7.935 1392.58
  7.999 1173.36
  8.218 1297.09
  8.325 1042.89
  8.369 2167.33
  8.382 1312.85
  8.61 2224.33
  8.995 1483.94
  9.265 2274.68
  9.701 2150.49
  9.752 1807.39];
units.WwN = {'g', '#'}; label.WwN = {'wet weight', 'yearly fecundity'};
temp.WwN = C2K(17.5); units.temp.WwN = 'K'; label.temp.WwN = 'temperature';
bibkey.WwN = {'pen1991biology1'};
comment.WwN = 'Temperature reaches a mimumum of 9 - 12 degrees C in July to August and a maximum of 18 - 26 degrees C between November and March. Mean temerpature (9 - 26) provided. ';

% length - wet weight
data.LWw_f = [ ... 
  56 0.627
  63 1.426
  69 1.466
  85 3.816
  76 2.339
  73 1.687
  79 2.661
  67 1.346
  65 1.35
  71 1.407
  66 1.676
  73 2.244
  63 0.85
  68 1.382
  70 1.502
  67 1.166
  78 2.63
  72 1.883
  75 1.914
  79 2.19
  76 2.069
  100 6.823
  74 2.567
  77 2.144
  68 1.86
  66 1.24
  61 0.97
  68 1.702
  71 1.71
  75 1.362
  65 1.434
  62 1.184
  63 0.987
  77 2.326
  66 1.246
  76 2.11
  61 0.983
  65 1.146
  73 2.195
  69 1.096
  72 1.793
  72 1.864
  71 1.735
  83 2.7
  65 1.533
  66 1.335
  59 0.71
  66 1.373
  64 1.178
  72 1.9
  63 1.444
  71 2.588
  72 2.054
  74 2.225
  80 2.717
  70 1.994
  71 1.99
  93 4.093
  86 4.02
  64 0.924
  76 1.925
  68 1.236
  72 2.31
  70 1.163
  81 3.247
  87 3.188
  60 0.906
  78 2.05
  77 2.031
  97 5.879
  79 1.404
  95 4.83
  104 4.778
  73 1.856
  68 1.309
  66 1.132
  55 0.595
  68 1.109
  76 2.581
  78 2.777
  68 1.738
  70 1.598
  65 1.542
  63 1.044
  59 0.968
  59 0.838
  69 1.364
  71 1.964
  66 1.669
  69 1.416
  68 1.4
  82 3.051
  79 2.702
  69 1.89
  76 2.112
  75 2.006
  75 1.92
  90 3.333
  64 1.608
  71 1.848
  76 2.333
  87 4.142
  95 5.809
  89 3.871
  68 1.08
  76 1.9
  70 1.62
  73 1.49
  60 0.85
  80 1.84
  67 1.08
  66 1.19
  70 1.36
  68 1.22
  64 1.05
  68 1.08
  74 1.43
  71 1.4
  68 1.26
  65 1.04
  60 0.82
  58 0.77
  63 0.97
  130 10.67
  91 3.51
  86 2.75
  70 1.45
  70 1.3
  105 4.35
  69 1.07
  83 2.58
  83 2.17
  100 6.48
  118 6.35
  63 1.06
  70 1.12
  68 0.95
  76 1.53
  75 1.5
  86 2.44
  110 6.75
  67 1.14
  73 1.46
  69 1.11
  65 0.92
  62 0.83
  59 0.6
  72 1.43
  78 1.61
  63 0.73
  58 0.59
  58 0.61
  110 6.18
  61 0.84
  58 0.64
  63 0.83
  55 0.58
  58 0.62
  57 0.57
  51 0.52
  55 0.6
  50 0.36
  89 2.99
  80 1.72
  120 5.68
  90 3.77
  90 3.22
  71 1.83
  71 1.95
  78 2.3
  92 3.56
  102 4.89
  58 0.81
  100 4.18
  78 2.13
  61 0.99
  83 2.58
  83 2.17
  100 6.48
  118 6.35
  63 1.06
  70 1.12
  68 0.95
  76 1.53
  75 1.5
  86 2.44
  110 6.75
  67 1.14
  73 1.46
  69 1.11
  65 0.92
  62 0.83
  59 0.6
  72 1.43
  76 1.89
  60 0.95
  57 0.79
  63 1.05
  64 1.17
  67 1.44
  62 1.08
  78 1.61
  63 0.73
  58 0.59
  58 0.61
  110 6.18
  61 0.84
  58 0.64
  63 0.83
  55 0.58
  58 0.62
  57 0.57
  51 0.52
  55 0.6
  50 0.36
  80 1.82
  73 1.64
  65 1.18
  65 0.89
  81 2.34
  90 2.77
  64 1.09
  62 0.89
  65 0.92
  70 1.13
  85 2.67
  78 2.25
  70 1.22
  61 0.74
  61 1
  56 0.65
  57 0.45
  76 2.2
  52 0.62
  70 2.3
  84 3.47
  70 1.96
  68 1.75
  65 1.4
  65 1.44
  65 1.6
  64 1.45
  70 1.92
  67 1.57
  94 3.33
  71 1.6
  67 1.22
  66 1.49
  78 2.52
  79 2.05
  76 2.32
  77 1.92
  57 0.9
  57 0.82
  58 0.95
  67 1.3
  62 0.87
  64 1.2
  79 2.59
  78 2.5
  80 2.85
  78 2.4
  68 1.4
  75 1.9
  80 2.3
  67 1.09
  73 1.87
  83 2.34
  106 5
  105 3.15
  90 3.07
  122 8.82
  80 1.67
  80 2.09
  90 3.28
  110 5.8
  90 2.38
  61 1.19
  100 4.76
  81 2.02
  66 1.22
  78 1.7
  83 2.24
  80 2.15
  69 1.27
  59 0.82
  55 0.69
  62 0.9
  62 0.89
  76 1.93
  62 1.37
  64 0.97
  61 0.69
  59 0.82
  55 0.69
  62 0.9
  62 0.89
  76 1.93
  62 1.37
  64 0.97
  61 0.69
  47 0.35
  44 0.48
  46 0.58
  63 0.93
  64 0.98
  104 3.98
  65 1.3
  66 1.28
  61 0.87
  60 0.92
  69 1.14
  96 3.78
  85 1.68
  61 0.82
  64 1.05
  62 1.03
  55 0.79
  68 1.2
  66 0.99
  67 1.1
  58 1
  117 4.43
  90 2.71
  86 2.16
  86 2.05
  101 3.88
  105 3.46
  65 1.09
  71 0.95
  58 0.78
  92 4.04
  100 4.88
  105 6.09
  71 1.53
  72 1.48
  103 6.06
  90 2.62
  107 6.92
  67 1.1
  77 2.29
  67 1.36
  60 0.86
  68 1.3
  70 1.17
  66 1.31
  58 0.9
  66 1.3
  75 1.5
  102 6.47
  120 9.67
  81 3.14
  86 3.45
  87 2.75
  102 6.7
  85 3.25
  73 1.68
  78 2.72
  95 4.78
  81 2.24
  72 1.85
  80 2.55
  73 2.09
  84 3.02
  78 2.88
  85 2.96
  73 1.76
  92 3.47
  80 2
  65 1.16
  76 1.67
  71 1.65
  67 1.22
  62 1.04
  74 1.73
  65 1.1
  58 0.71
  62 1.09
  73 1.45
  52 0.55
  69 1.35
  65 1.26
  74 1.54
  66 1.04
  67 1.12
  77 1.52
  62 1.05
  55 0.66
  51 0.44
  47 0.34
  42 0.26];
units.LWw_f = {'cm', 'g'}; label.LWw_f = {'length', 'wet weight'};
bibkey.LWw_f = {'Unpublished2023'};
comment.LWw_f = 'Combination from data collected in 2004 and 2006 from various sites in the south-west of Western Australia';

% length - wet weight
data.LWw_m = [ ... 
  59 0.775
  63 1.035
  53 0.723
  56 0.744
  60 0.956
  55 0.622
  57 0.905
  53 0.621
  56 0.717
  57 0.871
  58 0.934
  57 0.816
  53 0.548
  61 0.892
  59 0.872
  63 1.145
  56 0.639
  60 0.886
  53 0.618
  58 0.712
  59 0.883
  57 0.91
  58 1.029
  53 0.88
  58 0.791
  66 1.3
  79 2.115
  63 0.99
  68 1.632
  68 1.261
  73 1.75
  61 1.137
  65 0.981
  66 1.592
  59 0.832
  60 1.01
  68 1.685
  72 2.07
  61 1.14
  67 1.444
  60 0.976
  76 2.467
  61 0.847
  63 1.345
  56 0.913
  63 1.045
  53 0.522
  67 1.422
  56 0.712
  63 1.052
  61 0.879
  63 1.019
  80 2.353
  74 1.724
  65 1.297
  68 1.472
  71 1.528
  73 1.821
  54 0.523
  60 0.635
  66 1.076
  57 0.599
  64 0.839
  72 1.518
  53 0.507
  63 1.035
  55 0.705
  58 0.81
  62 1.124
  54 0.651
  52 0.683
  55 0.73
  55 0.605
  58 0.818
  54 0.588
  60 0.793
  56 0.677
  58 0.693
  57 0.783
  56 0.807
  52 1.078
  60 0.903
  63 1.094
  58 0.784
  55 0.769
  57 0.788
  59 1.048
  66 1.405
  68 1.018
  64 1.336
  60 1.013
  62 1.035
  65 1.289
  72 1.469
  64 1.462
  60 1.366
  62 1.228
  56 0.972
  67 1.59
  83 3.051
  64 1.139
  61 0.943
  63 1.384
  66 1.162
  55 0.716
  61 0.696
  70 1.404
  69 1.543
  60 1.32
  63 0.807
  66 1.014
  58 0.552
  62 0.717
  67 1.051
  55 0.673
  57 0.947
  59 1.041
  64 1.366
  56 0.591
  68 1.361
  67 1.461
  60 0.866
  65 1.233
  57 1.122
  62 1.157
  62 0.993
  71 1.726
  74 1.655
  72 2.511
  69 1.805
  63 0.811
  64 0.901
  61 1.027
  74 1.61
  60 0.971
  69 1.685
  80 3.193
  66 1.145
  74 1.72
  58 0.885
  61 1.194
  65 1.659
  60 1.024
  66 1.442
  70 1.67
  58 0.992
  66 1.568
  68 1.539
  76 2.859
  58 0.78
  90 3.1
  88 2.38
  93 3.57
  88 3.09
  80 2.2
  90 2.94
  86 2.84
  80 2.1
  85 2.9
  85 2.7
  91 3.2
  69 1.03
  60 0.78
  68 1.13
  60 0.73
  60 0.7
  56 0.65
  56 0.62
  72 1.46
  68 1.23
  81 2.32
  71 1.49
  65 1.04
  62 1.17
  69 1.03
  60 0.78
  65 1.05
  56 0.62
  55 0.73
  68 1.13
  60 0.73
  60 0.7
  56 0.65
  56 0.62
  82 2.31
  64 1.18
  89 3.29
  65 1.18
  74 1.93
  60 0.75
  60 0.86
  60 0.75
  68 1.31
  62 1.02
  55 0.65
  56 0.56
  90 3.23
  72 2.1
  79 2.46
  73 2.43
  79 2.82
  65 1.19
  75 3.22
  71 1.66
  66 1.06
  71 1.35
  74 1.89
  66 1.32
  63 0.98
  56 0.8
  51 0.95
  65 1.1
  61 0.87
  68 1.3
  62 1.12
  60 0.7
  80 2.14
  85 2.77
  81 2.27
  76 1.68
  82 2.08
  100 4.05
  65 1.28
  68 1.44
  71 1.4
  59 0.8
  65 1.18
  59 0.89
  89 2.39
  85 2.2
  77 1.54
  80 1.87
  58 0.66
  80 2.22
  57 0.59
  79 1.74
  81 1.75
  85 2.12
  63 0.72
  66 1.34
  55 0.7
  80 1.64
  75 1.39
  61 1.03
  70 1.27
  67 1.15
  61 0.87
  64 1.18
  76 1.7
  68 1.27
  74 1.54
  72 1.23
  78 1.76
  58 0.64
  51 0.47
  54 0.53];
units.LWw_m = {'cm', 'g'}; label.LWw_m = {'length', 'wet weight'};
bibkey.LWw_m = {'Unpublished2023'};
comment.LWw_m = 'Combination from data collected in 2004 and 2006 from various sites in the south-west of Western Australia';

%% set weights for all real data
weights = setweights(data, []);

%% set pseudodata and respective weights
[data, units, label, weights] = addpseudodata(data, units, label, weights);

%% pack auxData and txtData for output
auxData.temp = temp;
txtData.units = units;
txtData.label = label;
txtData.bibkey = bibkey;
txtData.comment = comment;

%% Group plots
set1 = {'tL_f','tL_m'}; comment1 = {'Data for females, males'};
metaData.grp.sets = {set1};
metaData.grp.comment = {comment1};

%% Links
metaData.links.id_CoL = '3F2WH'; % Cat of Life
metaData.links.id_EoL = '224692'; % Ency of Life
metaData.links.id_Wiki = 'Western_galaxias'; % Wikipedia
metaData.links.id_ADW = 'Galaxias_occidentalis'; % Anim Div. Web
metaData.links.id_Taxo = '174650'; % Taxonomicon

%% References
bibkey = 'Kooy2010'; type = 'Book'; bib = [ ...  % used in setting of chemical parameters and pseudodata
'author = {Kooijman, S.A.L.M.}, ' ...
'year = {2010}, ' ...
'title  = {Dynamic Energy Budget theory for metabolic organisation}, ' ...
'publisher = {Cambridge Univ. Press, Cambridge}, ' ...
'pages = {Table 4.2 (page 150), 8.1 (page 300)}, ' ...
'howpublished = {\url{http://www.bio.vu.nl/thb/research/bib/Kooy2010.html}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ' bib, '}'';'];
%
bibkey = 'Unpublished2023'; type = 'misc'; bib = [ ...
'author = {Donohue, CG}, ' ... 
'note = {Unpublished data on western minnow length, weight, sex and temperature. The data was collected from 2004 - 2006 at various sites in the south-west of Western Australia}, ' ... 
'year = {2023}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'gill1994larval'; type = 'article'; bib = [ ...
'author = {Gill, Howard S and Neira, Francisco J}, ' ... 
'title = {Larval descriptions of three galaxiid fishes endemic to south-western Australia: Galaxias occidentalis, Galaxiella munda and Galaxiella nigrostriata (Salmoniformes: Galaxiidae)}, ' ... 
'journal = {Marine and Freshwater Research}, ' ... 
'year = {1994}, ' ... 
'volume = {45}, ' ... 
'pages = {1307 - 1317}, ' ... 
'doi = {https://doi.org/10.1071/MF9941307}, ' ... 
'howpublished = {\url{https://www.publish.csiro.au/paper/MF9941307}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'morgan1998distribution'; type = 'article'; bib = [ ...
'author = {Morgan, David L and Gill, Howard S and Potter, Ian C}, ' ... 
'title = {Distribution, identification and biology of freshwater fishes in south-western Australia}, ' ... 
'journal = {Records of the Western Australian museum supplement}, ' ... 
'year = {1998}, ' ... 
'volume = {56}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'pen1991biology1'; type = 'article'; bib = [ ...
'author = {Pen, LJ and Potter, IC}, ' ... 
'title = {Biology of the western minnow, Galaxias occidentalis Ogilby (Teleostei: Galaxiidae), in a south-western Australian river: 1. Reproductive biology}, ' ... 
'journal = {Hydrobiologia}, ' ... 
'year = {1991}, ' ... 
'volume = {211}, ' ... 
'pages = {77-88}, ' ... 
'doi = {10.1007/BF00037364}, ' ... 
'howpublished = {\url{https://doi.org/10.1007/BF00037364}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
bibkey = 'pen1991biology2'; type = 'article'; bib = [ ...
'author = {Pen, LJ and Potter, IC}, ' ... 
'title = {Biology of the western minnow, Galaxias occidentalis Ogilby (Teleostei: Galaxiidae), in a south-western Australian river: 2. Size and age composition, growth and diet}, ' ... 
'journal = {Hydrobiologia}, ' ... 
'year = {1991}, ' ... 
'volume = {211}, ' ... 
'pages = {89-100}, ' ... 
'doi = {10.1007/BF00037365}, ' ... 
'howpublished = {\url{https://doi.org/10.1007/BF00037365}}'];
metaData.biblist.(bibkey) = ['''@', type, '{', bibkey, ', ', bib, '}'';'];
%
